---
- hosts: dbservers
  become: yes
  vars:
    currstate: present
  tasks:
    - name: Installation HTTPD
      action: apt name=apache2 state='{{currstate}}'
    - name: Install Git
      action: apt name=git state='{{currstate}}'
